# Generated by Django 3.2.23 on 2023-12-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artists',
            options={'verbose_name_plural': 'Artists'},
        ),
    ]
