# Generated by Django 3.2.23 on 2023-12-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20231111_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.SmallIntegerField(default=1),
        ),
    ]
